// Map of country codes to display names for all countries in CONTINENTS
export const COUNTRY_NAMES: Record<string, string> = {
  AD:"Andorra",AL:"Albania",AT:"Austria",AX:"Åland Islands",BA:"Bosnia",BE:"Belgium",BG:"Bulgaria",BY:"Belarus",CH:"Switzerland",CY:"Cyprus",CZ:"Czechia",DE:"Germany",DK:"Denmark",EE:"Estonia",ES:"Spain",FI:"Finland",FO:"Faroe Islands",FR:"France",GB:"United Kingdom",GG:"Guernsey",GI:"Gibraltar",GR:"Greece",HR:"Croatia",HU:"Hungary",IE:"Ireland",IM:"Isle of Man",IS:"Iceland",IT:"Italy",JE:"Jersey",LI:"Liechtenstein",LT:"Lithuania",LU:"Luxembourg",LV:"Latvia",MC:"Monaco",MD:"Moldova",ME:"Montenegro",MK:"North Macedonia",MT:"Malta",NL:"Netherlands",NO:"Norway",PL:"Poland",PT:"Portugal",RO:"Romania",RS:"Serbia",RU:"Russia",SE:"Sweden",SI:"Slovenia",SJ:"Svalbard",SK:"Slovakia",SM:"San Marino",UA:"Ukraine",VA:"Vatican City",
  AR:"Argentina",BO:"Bolivia",BR:"Brazil",CL:"Chile",CO:"Colombia",EC:"Ecuador",FK:"Falkland Islands",GF:"French Guiana",GY:"Guyana",PE:"Peru",PY:"Paraguay",SR:"Suriname",UY:"Uruguay",VE:"Venezuela",
  AG:"Antigua & Barbuda",AI:"Anguilla",AW:"Aruba",BB:"Barbados",BL:"Saint Barthélemy",BM:"Bermuda",BQ:"Caribbean NL",BS:"Bahamas",BZ:"Belize",CA:"Canada",CR:"Costa Rica",CU:"Cuba",CW:"Curaçao",DM:"Dominica",DO:"Dominican Rep.",GD:"Grenada",GL:"Greenland",GP:"Guadeloupe",GT:"Guatemala",HN:"Honduras",HT:"Haiti",JM:"Jamaica",KN:"Saint Kitts",KY:"Cayman Islands",LC:"Saint Lucia",MF:"Saint Martin",MQ:"Martinique",MS:"Montserrat",MX:"Mexico",NI:"Nicaragua",PA:"Panama",PM:"Saint Pierre",PR:"Puerto Rico",SV:"El Salvador",SX:"Sint Maarten",TC:"Turks & Caicos",TT:"Trinidad & Tobago",US:"United States",VC:"Saint Vincent",VG:"British V.I.",VI:"US V.I.",
  AF:"Afghanistan",AM:"Armenia",AZ:"Azerbaijan",BD:"Bangladesh",BH:"Bahrain",BN:"Brunei",BT:"Bhutan",CC:"Cocos Islands",CN:"China",CX:"Christmas Island",GE:"Georgia",HK:"Hong Kong",ID:"Indonesia",IL:"Israel",IN:"India",IO:"BIOT",IQ:"Iraq",IR:"Iran",JO:"Jordan",JP:"Japan",KG:"Kyrgyzstan",KH:"Cambodia",KP:"North Korea",KR:"South Korea",KW:"Kuwait",KZ:"Kazakhstan",LA:"Laos",LB:"Lebanon",LK:"Sri Lanka",MM:"Myanmar",MN:"Mongolia",MO:"Macau",MV:"Maldives",MY:"Malaysia",NP:"Nepal",OM:"Oman",PH:"Philippines",PK:"Pakistan",PS:"Palestine",QA:"Qatar",SA:"Saudi Arabia",SG:"Singapore",SY:"Syria",TH:"Thailand",TJ:"Tajikistan",TL:"Timor-Leste",TM:"Turkmenistan",TR:"Turkey",TW:"Taiwan",UZ:"Uzbekistan",VN:"Vietnam",YE:"Yemen",
  AS:"American Samoa",AU:"Australia",CK:"Cook Islands",FJ:"Fiji",FM:"Micronesia",GU:"Guam",KI:"Kiribati",MH:"Marshall Islands",MP:"N. Mariana Islands",NC:"New Caledonia",NF:"Norfolk Island",NR:"Nauru",NU:"Niue",NZ:"New Zealand",PF:"French Polynesia",PG:"Papua New Guinea",PN:"Pitcairn",PW:"Palau",SB:"Solomon Islands",TK:"Tokelau",TO:"Tonga",TV:"Tuvalu",UM:"US Minor Islands",VU:"Vanuatu",WF:"Wallis & Futuna",WS:"Samoa",
  AO:"Angola",BF:"Burkina Faso",BI:"Burundi",BJ:"Benin",BW:"Botswana",CD:"DR Congo",CF:"Central African Rep.",CG:"Congo",CI:"Côte d'Ivoire",CM:"Cameroon",CV:"Cape Verde",DJ:"Djibouti",DZ:"Algeria",EG:"Egypt",EH:"Western Sahara",ER:"Eritrea",ET:"Ethiopia",GA:"Gabon",GH:"Ghana",GM:"Gambia",GN:"Guinea",GQ:"Equatorial Guinea",GW:"Guinea-Bissau",KE:"Kenya",KM:"Comoros",LR:"Liberia",LS:"Lesotho",LY:"Libya",MA:"Morocco",MG:"Madagascar",ML:"Mali",MR:"Mauritania",MU:"Mauritius",MW:"Malawi",MZ:"Mozambique",NA:"Namibia",NE:"Niger",NG:"Nigeria",RE:"Réunion",RW:"Rwanda",SC:"Seychelles",SD:"Sudan",SH:"Saint Helena",SL:"Sierra Leone",SN:"Senegal",SO:"Somalia",SS:"South Sudan",ST:"São Tomé",SZ:"Eswatini",TD:"Chad",TG:"Togo",TN:"Tunisia",TZ:"Tanzania",UG:"Uganda",YT:"Mayotte",ZA:"South Africa",ZM:"Zambia",ZW:"Zimbabwe",
};
